### ISSUE TITLE
How to make demo video

### ISSUE THREAD

**Issue by lt-xiang** [rafael-weilharter/ATLAS-MVSNet#1]
Hi, may I know how you make this  dynamic demo video ?  I can get fused point clouds, but don't know how to generate this dynamic scene ?

**Comment by rafael-weilharter** [comment]
Hi, I generate the pointcloud with ATLAS-MVSNet, then render it in Open3D. I calculate the trajectory from the known camera poses and do a spline/slerp interpolation for the intermediate frames. Then it's easy to switch between the real TaT video and the pointcloud and depth images (both generated in Open3D).

**Comment by lt-xiang** [comment]
> Hi, I generate the pointcloud with ATLAS-MVSNet, then render it in Open3D. I calculate the trajectory from the known camera poses and do a spline/slerp interpolation for the intermediate frames. Then it's easy to switch between the real TaT video and the pointcloud and depth images (both generated in Open3D).

Hi rafael, thank you so much, would you mind share the complete code releated to the trajectory computation and slerp interpolation for my academic purpose ?(my email:  lintao.xiang@postgrad.manchester.ac.uk), this dynamic video is so fantastic.

**Comment by rafael-weilharter** [comment]
I decided to upload the code to git: https://github.com/rafael-weilharter/SPLERP
