### ISSUE TITLE
about decoder module

### ISSUE THREAD

**Issue by SenHuiYe** [rafael-weilharter/ATLAS-MVSNet#2]
Hello, after I read your code, I would like to ask why the decoding operation is needed? If I directly use the feature map extracted by HABNet without decoding operation, will it have any effect on the result?

**Comment by rafael-weilharter** [comment]
Hi, the decoder acts as cost volume regularization + classification (both via 3D convolutions). You could try skipping the regularization and directly classify the warped feature maps, but in our experiments using fewer 3D convolution layers yielded worse results.
