### ISSUE TITLE
About the HAB module

### ISSUE THREAD

**Issue by SenHuiYe** [rafael-weilharter/ATLAS-MVSNet#3]
Hello, I would like to ask you about the difference between Hybrid Attention Block and pure adding self-attention layer?

**Comment by rafael-weilharter** [comment]
Hi,
the HAB consists of several additional layers besides the pure self-attention layer and is constructed as a residual block: First, we use a convolutional layer with stride 2 followed by GroupNormalization and ReLU to drastically lower memory requirements for the subsequent self-attention layer. Second, we added the LayerScale for normalization after the self-attention layer.

More details can be found in the paper: https://elib.dlr.de/190995/1/weilharter2022Atlasmvsnet.pdf

![attention_block](https://user-images.githubusercontent.com/16336058/218724382-1014fc85-1672-4822-8612-bf27a85ed60b.png)

**Comment by SenHuiYe** [comment]
Thank you for your mentorship!I've learned a lot from your work!
