### ISSUE TITLE
About dtu evaluation

### ISSUE THREAD

**Issue by SenHuiYe** [rafael-weilharter/ATLAS-MVSNet#5]
Thanks for your work,first。I don’t seem to see the point cloud fusion file in your code. I would like to ask if your point cloud fusion is the fusion code of MVSNet?

**Comment by rafael-weilharter** [comment]
Hi, the fusion code is provided in the `test.py` file.
You can either use the `--dist=` flag to use the fusion by MVSNet, or substitute it with `--dyn=` to use the dynamic consistency checking. Further flags controlling the fusion settings are `--consistent=` for the number of consistent views and `--rel_dist=` for the relative depth error.
HTH
